# Nginx - react 간의 테스트를 위한 도커파일이다.

# 테스트에서는 공식 Node 이미지 최신버전을 사용한다.
FROM node:10.14.0

# React를 저장할 폴더를 만든다.
RUN mkdir www

# 이 후 명령어는 www폴더에서 실행한다.
WORKDIR /www

# React을 설치한다.
RUN npm install -g create-react-app

# React 프로젝트를 실행한다.
RUN create-react-app hello-react

# 이 후 명령어는 /www/hello-react폴더에서 실행한다.
WORKDIR /www/hello-react

# CMD는 명령어를 배열 형태로 배치해야하며
# 실제로 앱을 실행시키는 커맨드가 들어갑니다.
CMD ["npm", "start"]